slider_mapping:
  '0':
    - VALORANT-Win64-Shipping.exe
    - pathofexile_x64.exe
    - rocketleague.exe
  '1': msedge.exe
  '2': discord.exe
  '3': chrome.exe
  '4': master
invert_sliders: false
com_port: COM3
baud_rate: 9600
noise_reduction: default
